CREATE TABLE public.users (
    id UUID PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    password_updated_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT email_uk UNIQUE (email),
    CONSTRAINT users_status_check CHECK (
        status IN ('ACTIVE', 'PENDING', 'INACTIVE', 'LOCKED', 'SUSPENDED', 'DELETED')
    )
);

CREATE TABLE public.roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	role_type varchar(255) NOT NULL,
	CONSTRAINT role_type_uk UNIQUE (role_type),
	CONSTRAINT roles_pkey PRIMARY KEY (id),
	CONSTRAINT roles_role_type_check CHECK (((role_type)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying])::text[])))
);

CREATE TABLE public.user_roles (
	user_id UUID NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT role_user_uk UNIQUE (user_id, role_id),
	CONSTRAINT role_fk FOREIGN KEY (role_id) REFERENCES public.roles(id),
	CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);